#pragma once

#define INVALID_INDEX -1
#define MENU_CELL_HEIGHT 40
#define MENU_TEXT_LENGTH 30
#define TIMER_TEXT_LENGTH 20
#define TIMER_TEXT_HEIGHT 80
#define TIMER_TEXT_HEIGHT_SM 40
#define MS_PER_SECOND 1000
#define MS_PER_MINUTE 60000
